name: "Build PDF"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
#      - name: Install Python & Pygments
#        run: |
#          apt-get update
#          apt-get install -y python3 python3-pip
#          pip3 install pygments
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build PDF
        run: latexmk -pdf -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf -output-directory=./output -shell-escape -f ./src/main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: ./output/main.pdf
      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest PDF Build
          files: ./output/main.pdf
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}