jobs:
  build:
    runs-on: ubuntu-latest
    container: danteev/texlive:latest  # 预装 LaTeX 的 Docker 镜像

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        run: |
          latexmk -pdf -shell-escape -interaction=nonstopmode -halt-on-error main.tex

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf
