name: Build LaTeX PDF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache TeX Live
        uses: actions/cache@v4
        with:
          path: |
            ~/texlive
            /opt/texlive
          key: ubuntu-texlive-full-2023
          restore-keys: |
            ubuntu-texlive-full-2023

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl wget

      - name: Install TeX Live (Full)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz
          
          echo "解压目录结构："
          ls -l
          
          INSTALL_DIR=$(find . -maxdepth 1 -type d -name "install-tl-*" -print -quit)
          echo "进入安装目录：$INSTALL_DIR"
          cd "$INSTALL_DIR"
          
          echo "当前路径："
          pwd
          
          ./install-tl --version
          
          cat << EOF > profile
          selected_scheme scheme-full
          TEXDIR ~/texlive/2023
          tlpdbopt_autobackup 0
          tlpdbopt_install_docfiles 0
          tlpdbopt_install_srcfiles 0
          EOF
          
          ./install-tl -profile profile
          echo ~/texlive/2023/bin/x86_64-linux >> $GITHUB_PATH

      - name: Verify Installation
        run: |
          which pdflatex
          pdflatex --version

      - name: Compile Document
        run: |
          latexmk -pdf -shell-escape main.tex

      - uses: actions/upload-artifact@v4
        with:
          name: manuscript
          path: main.pdf